dailymenu/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from menu.views.menu import MenuListView

urlpatterns = []

urlpatterns += [
    path('', MenuListView.as_view(), name='index')
]

urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'^menu/', include('menu.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

menu/urls.py
from django.conf.urls import url

from menu.views.menu import MenuListView, MenuUpdateView, MenuCreateView, MenuDeleteView

app_name = 'menu'
urlpatterns = [
    url(r'^$', MenuListView.as_view(), name='list'),
    url(r'^create/$', MenuCreateView.as_view(), name='create'),
    url(r'^detail/(?P<pk>[0-9a-f-]+)/$', MenuListView.as_view(), name='detail'),
    url(r'^update/(?P<pk>[0-9a-f-]+)/$', MenuUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9a-f-]+)/$', MenuDeleteView.as_view(), name='delete'),
]

menu/models.py
import datetime
import uuid

from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.utils.translation import ugettext as _

from menu.utils import get_entries_for_menu


class Menu(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        unique=True
    )

    user = models.ForeignKey(
        to="auth.User",
        related_name='menus',
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    name = models.CharField(
        verbose_name=_('Name of the menu'),
        max_length=150
    )
    update_time = models.TimeField(
        verbose_name=_('Update hour'),
        help_text=_('This menu will be updated at time specified here.'),
        blank=True, null=True
    );

    url = models.URLField(
        verbose_name=_('Menu url'),
        blank=True, null=True
    )
    menu_element = models.CharField(
        max_length=150,
        blank=True, null=True
    )
    meal_element = models.CharField(
        max_length=150,
        blank=True, null=True
    )
    price_element = models.CharField(
        max_length=150,
        blank=True, null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def update_entries(self):
        entries = get_entries_for_menu(self)
        for entry in entries:
            MenuEntry.objects.create(
                name=entry[0].text,
                price=entry[1].text,
                menu=self
            )
        return entries

    def recent_entries(self, days=7, **kwargs):
        return self.entries.filter(created__gt=(timezone.now() - datetime.timedelta(days=days))).order_by('-created')

    def get_absolute_url(self):
        return reverse('index')

class MenuEntry(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        unique=True
    )

    menu = models.ForeignKey(
        to=Menu,
        related_name='entries',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    name = models.CharField(
        verbose_name=_('Name'),
        max_length=150
    )
    price = models.CharField(
        verbose_name=_('Price'),
        max_length=150
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

core/forms/mixins.py
class UserModelFormMixin(object):

    def __init__(self, *args, **kwargs):
        try:
            self.user = kwargs.pop('user')
        except KeyError as e:
            print("KeyError key %s not in kwargs." % e)
        super().__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        obj = super().save(*args, **kwargs)

        if hasattr(self, 'user'):
            self.instance.user = self.user
            self.instance.save()

        return obj

menu/forms.py
from django import forms

from core.forms.mixins import UserModelFormMixin
from menu.models import Menu


class MenuModelForm(UserModelFormMixin, forms.ModelForm):
    class Meta:
        model = Menu
        fields = [
            'name',
            'url',
            'update_time',
            'menu_element',
            'meal_element',
            'price_element'
        ]

core/views/authenticated.py
from core.views.base import BaseCreateView, BaseDeleteView, BaseDetailView, BaseListView, BaseUpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

class AuthenticatedListView(LoginRequiredMixin, BaseListView):
    pass


class AuthenticatedCreateView(LoginRequiredMixin, BaseCreateView):
    pass


class AuthenticationDeleteView(LoginRequiredMixin, BaseDeleteView):
    pass


class AuthenticationDetailView(LoginRequiredMixin, BaseDetailView):
    pass


class AuthenticationUpdateView(LoginRequiredMixin, BaseUpdateView):
    pass

core/views/base.py
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)


class BaseListView(ListView):
    pass

class BaseDetailView(DetailView):
    pass

class BaseCreateView(CreateView):
    pass

class BaseUpdateView(UpdateView):
    pass

class BaseDeleteView(DeleteView):
    pass

core/views/mixins.py
class UserFormViewMixin(object):

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs.update({'user': self.request.user})
        return kwargs

menu/views/menu.py
import datetime

from django.urls import reverse_lazy
from django.utils import timezone

from core.views import authenticated
from core.views.mixins import UserFormViewMixin
from menu.forms import MenuModelForm
from menu.models import Menu


class MenuListView(authenticated.AuthenticatedListView):
    model = Menu

    def get_queryset(self):
        return Menu.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(MenuListView, self).get_context_data(**kwargs)
        context['date_from'] = timezone.now()
        context['date_to'] = timezone.now() - datetime.timedelta(days=7)
        return context


class MenuCreateView(UserFormViewMixin, authenticated.AuthenticatedCreateView):
    model = Menu
    form_class = MenuModelForm


class MenuUpdateView(UserFormViewMixin, authenticated.AuthenticationUpdateView):
    model = Menu
    form_class = MenuModelForm

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.update_entries()
        return super().post(request, *args, **kwargs)


class MenuDeleteView(authenticated.AuthenticationDeleteView):
    model = Menu
    success_url = reverse_lazy('index')

templates/base.html
{% load staticfiles pipeline %}

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>DailyMenu</title>

        {% stylesheet 'css' %}

    </head>

    <body>
        <section role="navigation">
            <nav class="navbar navbar-inverse bg-inverse navbar-toggleable-sm static-top">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">DailyMenu</a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="navbar-nav float-left">
                            <a href="{% url 'menu:create' %}" class="nav-link">manage</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav float-right">
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="#">Logged as: {{request.user.username}}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="#">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </section>

        <br>

        <div class="container">
            {% block 'main-content' %}
            {% endblock 'main-content' %}
        </div>

        <footer>
            {% block 'footer' %}
            {% endblock 'footer' %}
        </footer>

        {% javascript 'js' %}
    </body>
</html>

templates/menu/menu_confirm_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block 'main-content' %}

<div class="container">
    <h1 class="title">
        Delete menu {{ object.name }}
    </h1>
</div>

<div class="container">
    <div class="content">
        <form action="" method="POST">
            {% csrf_token %}
            <p>Are your sure to delete this menu?</p>
            {% buttons %}
                <button type="submit" class="btn btn-primary">Confirm</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock 'main-content' %}

templates/menu/menu_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block 'main-content' %}

<div class="container">
    <h1 class="title">
        Update menu
    </h1>
</div>

<div class="container">
    <div class="content">
        <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock 'main-content' %}

templates/menu/menu_list.html
{% extends "base.html" %}

{% block 'main-content' %}

<div class="container">
    ({{date_to}} - {{date_from}})
</div>

<table class="table table-sm">
    {% for menu in object_list %}
        <thead>
            <tr>
                <th>
                    <h4>
                        {{menu.name}}
                    </h4>
                    <span class="badge badge-success">
                        updated at {{menu.updated}}
                    </span>&nbsp;
                    <span class="badge badge-primary">
                        url: <a href="{{menu.url}}" class="text-white">{{menu.url}}</a>
                    </span>
                </th>
                <th class="text-right">
                    <a class="btn btn-sm btn-primary" href="{% url 'menu:update' pk=menu.id %}">Edit</a>&nbsp;
                    <a class="btn btn-sm btn-danger" href="{% url 'menu:delete' pk=menu.id %}">Delete</a>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for entry in menu.recent_entries %}
                <tr>
                    <td>{{entry.name}}</td>
                    <td class="text-right">{{entry.price}}</td>
                </tr>
            {% endfor %}
        </tbody>
    {% endfor %}
</table>

{% endblock 'main-content' %}